spring.application.name=ewallet
stripe.secret.key=sk_test_51TE1vXDkKjDbG1L0l6VJfeiztgiw7G8APgZXgDlHoCXJuEZzE9ZX4hWU8iLoxLoUvlNV5A64NnrNFSsGRxVoplvr003pGbrbPR
stripe.webhook.secret=whsec_2b051cea3faa525b2267faa4d475fbedf005f587b561ebdf56b9baac71e8577b